# TD5 - Les classes

## Exercice 1

Créer une classe `GoT`.

Celle-ci va prendre une liste de noms de personnage en entrée, stockée dans un attribut `alive` (qui sera un set). Le constructeur initialisera aussi un attribut `dead` avec un set vide.

Elle aura:
- une méthode `kill`, qui prendra un nom en entrée et le passera dans la liste `dead` si ce nom est dans `alive`, affichera `{NOM} est déjà tué` si il est déjà dans `dead`, et ne fera rien sinon.
- une méthode `appear` qui prendra un nom de personnage en entrée et le rajoutera dans `alive` si il n'est ni dans `alive`, ni dans `dead`
- une méthode `kill_random`, qui tuera une personne au hasard

In [1]:
import random


class GoT:
    
    def __init__(self, names):
        self.alive = set(names)
        self.dead = set()
        
    def appear(self, name):
        if name not in self.dead:
            self.alive.add(name)
            
    def kill(self, name):
        if name in self.alive:
            self.alive.remove(name)
            self.dead.add(name)
        elif name in self.dead:
            print(f'{name} is already dead')
            
    def kill_random(self):
        if len(self.alive):
            to_kill = random.sample(self.alive, 1)[0]
            self.alive.remove(to_kill)
            self.dead.add(to_kill)

In [2]:
# Test
env = GoT(['eddard', 'catelyn', 'robb', 'sansa', 'arya', 'brandon',
        'rickon', 'theon', 'robert', 'cersei', 'tywin', 'jaime',
        'tyrion', 'shae', 'bronn', 'lancel', 'joffrey', 'sandor',
        'varys', 'renly'])
print(env.alive, env.dead)
env.kill('joffrey')
print(env.alive, env.dead)
env.kill('joffrey')
print(env.alive, env.dead)
env.appear('daenerys')
print(env.alive, env.dead)
for _ in range(50):
    env.kill_random()
print(env.alive, env.dead)

{'tyrion', 'varys', 'theon', 'cersei', 'shae', 'robert', 'lancel', 'brandon', 'tywin', 'rickon', 'arya', 'robb', 'joffrey', 'catelyn', 'sandor', 'sansa', 'renly', 'jaime', 'bronn', 'eddard'} set()
{'tyrion', 'varys', 'theon', 'cersei', 'shae', 'robert', 'lancel', 'brandon', 'tywin', 'rickon', 'arya', 'robb', 'catelyn', 'sandor', 'sansa', 'renly', 'jaime', 'bronn', 'eddard'} {'joffrey'}
joffrey is already dead
{'tyrion', 'varys', 'theon', 'cersei', 'shae', 'robert', 'lancel', 'brandon', 'tywin', 'rickon', 'arya', 'robb', 'catelyn', 'sandor', 'sansa', 'renly', 'jaime', 'bronn', 'eddard'} {'joffrey'}
{'tyrion', 'varys', 'theon', 'cersei', 'shae', 'robert', 'lancel', 'brandon', 'tywin', 'daenerys', 'rickon', 'arya', 'robb', 'catelyn', 'sandor', 'sansa', 'renly', 'jaime', 'bronn', 'eddard'} {'joffrey'}
set() {'varys', 'tyrion', 'theon', 'cersei', 'shae', 'robert', 'lancel', 'brandon', 'tywin', 'daenerys', 'rickon', 'arya', 'robb', 'joffrey', 'catelyn', 'sandor', 'renly', 'sansa', 'jaime', '

## Exercie 2

Implémenter une Stack. Une stack est une structure de données LIFO (last in firs out). C'est à dire qu'il stocke les données dans l'order d'arrivé, et ressort le dernier arrivé quand on lui demande.

Votre Stack doit avoir deux méthodes en plus du constructeur:
- init qui crée une stack vide
- add qui rajoute un élément à la stack
- pop qui renvoit le dernier élément rentré et le supprime

Indice: les listes ont une méthode pop

In [3]:
class Stack:
    
    def __init__(self):
        self.stack = []
        
    def add(self, elem):
        self.stack.append(elem)
        
    def pop(self):
        return self.stack.pop()

In [4]:
stack = Stack()

for i in range(10):
    stack.add(i)

for _ in range(10):
    print(stack.pop())

9
8
7
6
5
4
3
2
1
0


## Exercice 3

Créer une Queue. Une queue est une structure de données FIFO (first in first out). C'est à dire qu'il stocke les données dans l'ordre d'arrivé, et qu'il ressort dans l'ordre d'arrivé.

Votre queue doit avoir trois méthodes en plus du constructeur:
- init qui crée une queue vide avec une taille maximale
- add qui prend un argument et le stocke
- pop qui retourne le premier élément
- full qui renvoit True si la queue est pleine

Attention, vous ne devez pas supprimer un élément d'une liste, sauf avec pop, qui supprime le dernier élément de la liste.

Indice: Vous pouvez utiliser deux listes pour gérer la Queue. La première stocke les valeurs dans l'ordre d'entrée, et une autre dans le sens inverse. Lorsque l'on ajoute un élément, on l'append à la liste d'entrée. Lorsque l'on pop un élément, si la deuxième liste n'est pas vide, on retourne le dernier élément de cette liste. Si celle-ci est vide, on transfert la première liste dans la seconde, en inversant le sens.

In [5]:
class Queue:
    
    def __init__(self, max_size):
        self.in_queue = []
        self.out_queue = []
        self.max_size = max_size
        
    def add(self, elem):
        if len(self) < self.max_size:
            self.in_queue.append(elem)
        else:
            print('The queue is full!')
            
    def _swap(self):
        if self.out_queue:
            return
        self.out_queue = self.in_queue[::-1]
        self.in_queue = []
        
    def pop(self):
        if len(self):
            self._swap()
            return self.out_queue.pop()
        else:
            print('The queue is empty!')
            
    def __len__(self):
        return len(self.in_queue) + len(self.out_queue)
    
    def full(self):
        return len(self) == self.max_size

In [6]:
q = Queue(10)
for i in range(5):
    q.add(i)
for i in range(2):
    print(q.pop())
for i in range(5, 12):
    q.add(i)
print(q.full())
for _ in range(8):
    print(q.pop())
print(q.full())

0
1
True
2
3
4
5
6
7
8
9
False


## Exercice 4

Créer une linked list. Une linked list est une liste qui peut supprimer un élément en son centre en un temps presque constant. Pour cela, chaque élément contient un lien vers le suivant.

Votre linked list devra contenir ces méthodes:
- un constructeur qui initialisera une liste vide
- add_first, qui ajoutera un élément en début de liste
- add_last, qui ajoutera un élément en fin de liste
- \_\_len\_\_ pour faire fonctionner la fonction len
- \_\_str\_\_ pour faire fonctionner la fonction print
- remove, qui prendra un élément et supprimera la première occurence

Indice1: vous aller devoir utiliser une classe pour un noeud d'une linked list.

Indice2: la linked list devra garder la tête de celle ci

In [7]:
class LinkedNode:
    
    def __init__(self, elem, next_elem=None):
        self.elem = elem
        self.next_elem = next_elem
        
        
class LinkedList:
    
    def __init__(self):
        self.head = None
        self.size = 0
        
    def add_first(self, elem):
        self.head = LinkedNode(elem, self.head)
        self.size += 1
        
    def add_last(self, elem):
        if self.head is None:
            self.head = LinkedNode(elem)
            self.size = 1
            return
        current_node = self.head
        while current_node.next_elem is not None:
            current_node = current_node.next_elem
        current_node.next_elem = LinkedNode(elem)
        self.size += 1
    
    def __len__(self):
        return self.size
    
    def __str__(self):
        if self.head is None:
            return 'None'
        current_str = '['
        current_node = self.head
        while current_node is not None:
            current_str += str(current_node.elem) + ', '
            current_node = current_node.next_elem
        return current_str[:-2] + ']'
    
    def remove(self, elem):
        if self.head is None:
            return
        if self.head.elem == elem:
            self.head = self.head.next_elem
            self.size -= 1
            return
        current_node = self.head
        next_node = current_node.next_elem
        while next_node is not None:
            if next_node.elem == elem:
                current_node.next_elem = next_node.next_elem
                self.size -= 1
                return
            current_node = next_node
            next_node = next_node.next_elem

In [8]:
l = LinkedList()

for i in range(5):
    l.add_last(i)
    print(l)
    
for i in range(5, 10):
    l.add_first(i)
    print(l)

print(len(l))
for i in range(3):
    l.remove(i)
    print(l)
print(len(l))
l.remove(4)
print(l)
l.remove(9)
print(l)
print(len(l))

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[5, 0, 1, 2, 3, 4]
[6, 5, 0, 1, 2, 3, 4]
[7, 6, 5, 0, 1, 2, 3, 4]
[8, 7, 6, 5, 0, 1, 2, 3, 4]
[9, 8, 7, 6, 5, 0, 1, 2, 3, 4]
10
[9, 8, 7, 6, 5, 1, 2, 3, 4]
[9, 8, 7, 6, 5, 2, 3, 4]
[9, 8, 7, 6, 5, 3, 4]
7
[9, 8, 7, 6, 5, 3]
[8, 7, 6, 5, 3]
5


## Exercice 5

Implémenter une classe modélisant un sudoku.

In [9]:
import numpy as np
# numpy permet de créer des vecteurs, c'est à dire des sortes de listes en plusieurs dimension de taille presque fixe,
# mais dont l'accès à un élément et la modification est instantannée

class Sudoku:
    """
    We will create a sudoku. We will modelise it with a matrice (numpy array).
    We will give a number to each square as follow
    
         0  |  1  |  2  
       -----------------
         3  |  4  |  5
       -----------------
         6  |  7  |  8
         
    A case not filled will contains -1
    """
    
    
    
    def __init__(self, values=None):
        if values is None:
            self.values = (np.ones((9, 9)) * -1).astype(int)
            # créer une matrice de taille 9 * 9 avec que des 1, que l'on multiylie par -1
        else:
            self.values = np.array(values).astype(int)
            if not self.check():
                raise ValueError('Wrong value passed as input.')
                
    def check(self):
        """
        Check if the sudoku is correct, i.e. there is no doublons on rows, columns, or squares
        """
        for i in range(9):
            current_check = self.check_row(i) and self.check_column(i) and self.check_square(i)
            if not current_check:
                return False
        return True
    
    def check_row(self, i):
        """
        Check if there is no doublon on the i-th row
        """
        appeared = set()
        for n in self.values[i, :]:
            if n != -1 and n in appeared:
                return False
            appeared.add(n)
        return True
            
    def check_column(self, i):
        """
        Check if there is no doublon on the i-th column
        """
        appeared = set()
        for n in self.values[:, i]:
            if n != -1 and n in appeared:
                return False
            appeared.add(n)
        return True
            
    def check_square(self, i):
        """
        Check if there is no doublon on the i-th square
        """
        appeared = set()
        row = i // 3
        column = i % 3
        for n in self.values[3 * row: 3 * (row + 1), 3 * column: 3 * (column + 1)].flatten():
            if n != -1 and n in appeared:
                return False
            appeared.add(n)
        return True
            
    def mark(self, i, j, n):
        """
        Put a n in the i-th row, j-th column.
        If it breaks the logic of the sudoku, will do nothing and return False.
        Return True otherwise
        """
        if (n != -1) and (n < 1 or n > 9):
            raise ValueError('Wrong value for n')
        old = self.values[i, j]
        self.values[i, j] = n
        current_square = (i // 3) * 3 + j // 3
        if not(self.check_row(i) and self.check_column(j) and self.check_square(current_square)):
            print('This move is impossible')
            self.values[i, j] = old
            return False
        return True
    
    def show(self):
        print(self.values)

In [10]:
game = Sudoku()
game.show()
game.mark(0, 0, 1)
game.mark(0, 1, 4)
game.show()
game.mark(0, 5, 1)
game.mark(5, 1, 4)
game.mark(2, 2, 1)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]
[[ 1  4 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]
This move is impossible
This move is impossible
This move is impossible


False